### ISSUE TITLE
Modflow 6 well edge case when located on partition border

### ISSUE THREAD

**Issue by JoerivanEngelen** [Deltares/imod-python#1212]
When Well's are located on the edge of a partition border, wells are located to both partitions for unstructured grids, and since https://github.com/Deltares/imod-python/pull/1189 also for stuctured grids.

After a discussion with @Huite, I concluded that the easiest way forward is probably to add a post-processing step to ``Modflow6Simulation.split``, which looks for duplicate well entries (maybe by index or 'id' if possible) amongst different model partitions and select one. 

Note: Wells are still grid agnostic after splitting, assigning wells to cells occurs in the call to ``Modflow6Simulation.write()``.

**Comment by LuukBlom** [comment]
Did some investigation while working on fixing this: https://github.com/Deltares/iMOD-Documentation/actions/runs/31402903649/job/93502018851?pr=88

Wanted to create a new issue for this, but then found this one.
Just updating this with my findings, reproducer and workaround.

---

## Problem

After calling `simulation.split(submodel_labels)` and then `simulation_split.write(...)`, writing fails with:

```text
KeyError: '"['layer'] not in index"
Error occured while writing wel'
```

This specific problem only reproduces on **Linux**; the identical script runs without error on **Windows**.

### Root cause

A single well is placed at a location that `submodel_labels` assigns to partition `GWF_1` (confirmed via `submodel_labels.sel(x=x_well, y=y_well, method="nearest")` → `1`).

After `split()`, however, **`GWF_0` also ends up with a `wel` package** containing this same well, even though `GWF_0`'s `idomain` at that `(x, y)` is fully inactive (all zeros across all layers). This looks like the well is being included in a neighboring partition's package, likely due to a bounding-box/tolerance step in the split/well-clipping logic, without checking whether it actually overlaps an active cell in that partition.

When `Modflow6Model._write` → `_prepare_wel_for_mf6` → `Well._to_mf6_pkg` runs for `GWF_0`, the layer-assignment step finds no active cells and returns a dataframe with no `layer` column. `_create_cellid` then crashes trying to select `["x", "y", "layer"]`:

```python
# imod/mf6/wel.py, _create_cellid
d_for_cellid = unique_assigned_wells[["x", "y", "layer"]].to_dict("list")
```

### Why this seems to be platform-dependent

I suspect a step in `create_partition_labels` and/or the well-to-partition clipping logic in `split()` has floating-point or ordering behavior that differs between platforms (e.g. via scipy/rasterio/PyMetis), causing a well near a partition boundary to be attached to an extra partition on Linux but not on Windows. I haven't dug further into the split internals to confirm exactly where this happens. Good idea to add tests for this.

### Reproducer

Extracted relevant code from https://github.com/Deltares/iMOD-Documentation/blob/main/docs/tutorial_Hondsrug.ipynb

reproducer + workaround

<details>

```python
import imod
from imod.prepare import create_partition_labels

tmpdir = imod.util.temporary_directory()

simulation = imod.data.hondsrug_simulation(tmpdir / "hondsrug_saved")

# Ensure xt3d is not used
simulation["GWF"]["npf"].set_xt3d_option(is_xt3d_used=False, is_rhs=False)
gwf_model = simulation["GWF"]

# Add a well package (this is the package that fails to write after split)
x_well = 246000.0
y_well = 560000.0
well = imod.mf6.Well(
    screen_top=[-13.0],
    screen_bottom=[-50.0],
    y=[y_well],
    x=[x_well],
    rate=[-60000.0],
)
simulation["GWF"]["wel"] = well

# Partition and write
idomain = gwf_model["dis"]["idomain"]
npartitions = 4
submodel_labels = create_partition_labels(idomain, npartitions=npartitions)

simulation_split = simulation.split(submodel_labels)

# Inspect what submodel keys actually exist, and find each one's wel package
print("simulation_split keys:", list(simulation_split.keys()))
print("\nsubmodel_labels at well location:")
print(submodel_labels.sel(x=x_well, y=y_well, method="nearest").values)

for key in simulation_split.keys():
    model = simulation_split[key]
    if hasattr(model, "keys") and "wel" in model.keys():
        wel = model["wel"]
        idomain_part = model["dis"]["idomain"]
        top = model["dis"]["top"]
        bottom = model["dis"]["bottom"]
        k = model["npf"]["k"]

        print("\n---", key, "---")
        try:
            idomain_at_well = idomain_part.sel(x=x_well, y=y_well, method="nearest")
            print("idomain at well location (per layer):", idomain_at_well.values)
        except Exception as e:
            print("idomain lookup failed:", e)

        # Reproduce to_mf6 in isolation for this partition
        try:
            mf6_wel = wel.to_mf6(idomain_part, top, bottom, k)
            print("to_mf6 SUCCEEDED, cellid:")
            print(mf6_wel["cellid"].values)
        except Exception as e:
            print("to_mf6 FAILED:", repr(e))

# # Workaround: drop wel packages where the well has no overlap with any active cell
# # Uncommenting this fixes the error.
# for key in simulation_split.keys():
#     model = simulation_split[key]
#     if hasattr(model, "keys") and "wel" in model.keys():
#         idomain_part = model["dis"]["idomain"]
#         idomain_at_well = idomain_part.sel(x=x_well, y=y_well, method="nearest")
#         if (idomain_at_well == 1).sum() == 0:
#             print(f"Dropping phantom wel package from {key}")
#             model.pop("wel")

modeldir = tmpdir / "partitioning"
simulation_split.write(modeldir)  # <-- fails here with KeyError on 'layer'

```

</details>

Output

<details>

```text
blom@WSU-5CG4011HHC: ~/Projects/iMOD-Documentation @ release_1_1$ pixi run python docs/debug.py
Unzipping contents of '/home/blom/.cache/imod/hondsrug-simulation.zip' to '/tmp/tmpkxz7s37y/hondsrug_saved'
/home/blom/Projects/iMOD-Documentation/.pixi/envs/default/lib/python3.14/site-packages/xarray/core/duck_array_ops.py:277: RuntimeWarning: invalid value encountered in cast
  return data.astype(dtype, **kwargs)
/home/blom/Projects/iMOD-Documentation/.pixi/envs/default/lib/python3.14/site-packages/xarray/core/duck_array_ops.py:277: RuntimeWarning: invalid value encountered in cast
  return data.astype(dtype, **kwargs)
/home/blom/Projects/iMOD-Documentation/.pixi/envs/default/lib/python3.14/site-packages/xarray/core/duck_array_ops.py:277: RuntimeWarning: invalid value encountered in cast
  return data.astype(dtype, **kwargs)
/home/blom/Projects/iMOD-Documentation/.pixi/envs/default/lib/python3.14/site-packages/xarray/core/duck_array_ops.py:277: RuntimeWarning: invalid value encountered in cast
  return data.astype(dtype, **kwargs)
simulation_split keys: ['solver', 'time_discretization', 'GWF_0', 'GWF_1', 'GWF_2', 'GWF_3', 'split_exchanges']

submodel_labels at well location:
1

--- GWF_0 ---
idomain at well location (per layer): [0 0 0 0 0 0 0 0 0 0 0 0 0]
to_mf6 FAILED: AttributeError("'Well' object has no attribute 'to_mf6'")

--- GWF_1 ---
idomain at well location (per layer): [ 1 -1  1 -1  1  1  1 -1  1 -1  1 -1  1]
to_mf6 FAILED: AttributeError("'Well' object has no attribute 'to_mf6'")
Traceback (most recent call last):
  File "/home/blom/Projects/iMOD-Documentation/.pixi/envs/default/lib/python3.14/site-packages/imod/mf6/model.py", line 565, in _write
    mf6_well_pkg = self._prepare_wel_for_mf6(pkg_name, validate_context)
  File "/home/blom/Projects/iMOD-Documentation/.pixi/envs/default/lib/python3.14/site-packages/imod/logging/logging_decorators.py", line 32, in wrapper
    return_value = fun(*args, **kwargs)
  File "/home/blom/Projects/iMOD-Documentation/.pixi/envs/default/lib/python3.14/site-packages/imod/mf6/model.py", line 476, in _prepare_wel_for_mf6
    return pkg._to_mf6_pkg(
           ~~~~~~~~~~~~~~~^
        idomain,
        ^^^^^^^^
    ...<3 lines>...
        validate_context,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/blom/Projects/iMOD-Documentation/.pixi/envs/default/lib/python3.14/site-packages/imod/mf6/wel.py", line 530, in _to_mf6_pkg
    ds["cellid"] = self._create_cellid(assigned_wells, idomain)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/blom/Projects/iMOD-Documentation/.pixi/envs/default/lib/python3.14/site-packages/imod/mf6/wel.py", line 372, in _create_cellid
    d_for_cellid = unique_assigned_wells[["x", "y", "layer"]].to_dict("list")
                   ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/blom/Projects/iMOD-Documentation/.pixi/envs/default/lib/python3.14/site-packages/pandas/core/frame.py", line 4384, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/blom/Projects/iMOD-Documentation/.pixi/envs/default/lib/python3.14/site-packages/pandas/core/indexes/base.py", line 6302, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/blom/Projects/iMOD-Documentation/.pixi/envs/default/lib/python3.14/site-packages/pandas/core/indexes/base.py", line 6355, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['layer'] not in index"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/blom/Projects/iMOD-Documentation/docs/debug.py", line 72, in <module>
    simulation_split.write(modeldir)  # <-- fails here with KeyError on 'layer'
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/blom/Projects/iMOD-Documentation/.pixi/envs/default/lib/python3.14/site-packages/imod/logging/logging_decorators.py", line 32, in wrapper
    return_value = fun(*args, **kwargs)
  File "/home/blom/Projects/iMOD-Documentation/.pixi/envs/default/lib/python3.14/site-packages/imod/mf6/simulation.py", line 380, in write
    value._write(
    ~~~~~~~~~~~~^
        modelname=key,
        ^^^^^^^^^^^^^^
    ...<2 lines>...
        validate_context=self._validation_context,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/blom/Projects/iMOD-Documentation/.pixi/envs/default/lib/python3.14/site-packages/imod/logging/logging_decorators.py", line 32, in wrapper
    return_value = fun(*args, **kwargs)
  File "/home/blom/Projects/iMOD-Documentation/.pixi/envs/default/lib/python3.14/site-packages/imod/mf6/model.py", line 580, in _write
    raise type(e)(f"{e}\nError occured while writing {pkg_name}")
KeyError: '"[\'layer\'] not in index"\nError occured while writing wel'
```

</details>
