### ISSUE TITLE
Error using imod.prepare.laplace_interpolate

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#179]
In GitLab by @Huite on Jun 1, 2021, 15:42

Copied from:

https://oss.deltares.nl/web/imod/forum/-/message_boards/view_message/4174264

> Hiii,
> 
> I am trying to use the laplace-interpolation function but run into the following error. I am sorry for this long message, I guessed all of it is relevant though. My input is the follwing, the grid resolution is 100 m:
> 
> `idf_laplace = im.prepare.laplace_interpolate(xr_idf, xr_mask, close= 1, mxiter= 5, iter1=50, relax=0.98)`
> 
> Did anyone have a similar problem before? Did I use the wrong values for the paramters "close", "mxiter", "iter1" and "relax" ? Or is maybe my idf not suited for this kind of interpolation?
> 
> Kind regards,
> Kristina

```
Traceback (most recent call last):
  File "C:/Users/Kristina/PycharmProjects/imod-2/main.py", line 24, in <module>
    idf_laplace = im.prepare.laplace_interpolate(xr_idf, xr_mask, close= 1, mxiter= 5, iter1= 50, relax=0.98)
  File "C:\Users\Kristina\anaconda3\envs\imod-2\lib\site-packages\imod\prepare\spatial.py", line 165, in laplace_interpolate
    converged = solver.solve(
  File "C:\Users\Kristina\anaconda3\envs\imod-2\lib\site-packages\imod\prepare\pcg.py", line 153, in solve
    hnew, res, bigh, bigr, indices_bigh, indices_bigr = calculate_heads(
  File "C:\Users\Kristina\anaconda3\envs\imod-2\lib\site-packages\numba\core\dispatcher.py", line 420, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\Kristina\anaconda3\envs\imod-2\lib\site-packages\numba\core\dispatcher.py", line 361, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function setitem>) found for signature:
 
 >>> setitem(readonly array(float64, 1d, C), int64, float64)
 
There are 16 candidate implementations:
     - Of which 14 did not match due to:
     Overload of function 'setitem': File: <numerous>: Line N/A.
       With argument(s): '(readonly array(float64, 1d, C), int64, float64)':
      No match.
     - Of which 2 did not match due to:
     Overload in function 'SetItemBuffer.generic': File: numba\core\typing\arraydecl.py: Line 171.
       With argument(s): '(readonly array(float64, 1d, C), int64, float64)':
      Rejected as the implementation raised a specific error:
        TypeError: Cannot modify value of type readonly array(float64, 1d, C)
  raised from C:\Users\Kristina\anaconda3\envs\imod-2\lib\site-packages\numba\core\typing\arraydecl.py:177

During: typing of setitem at C:\Users\Kristina\anaconda3\envs\imod-2\lib\site-packages\imod\prepare\pcg.py (648)

File "..\..\..\..\anaconda3\envs\imod-2\lib\site-packages\imod\prepare\pcg.py", line 648:
def calculate_heads(ibound, nlay, nrow, ncol, nrc, alpha, p, bigh, bigr, hnew, res, v):
    <source elided>
                    kh = k
                hnew[n] = hnew[n] + hchgn
                ^
```

**Comment by Manangka** [comment]
In GitLab by @Huite on Jun 1, 2021, 16:18

Okay, turns out this is actually the issue I already was aware of: apparently giving any kind of ibound breaks it...

I should be able to fix it relatively quickly. If you want a solution now, simply do not pass the xr_mask argument (it's optional).
It will then interpolate the entire extent, but you can apply your mask again by using xarray's where function. 

```python
idf_laplace = im.prepare.laplace_interpolate(xr_idf, close= 1, mxiter= 5, iter1=50, relax=0.98)
idf_laplace = idf_laplace.where(xr_mask)
```

I'm not sure what you're interpolating here, but a "close" of 1 is likely not accurate enough. To give a little bit of context, this function basically runs a single layer groundwater model (that's the Laplace equation), treating the cells with values as constant head cells. The "close" argument is exactly the same one as the MODFLOW HCLOSE argument.

Let's say you're interpolating an elevation dataset: if you'd like a numerical error of maximum 1 m on the result, you'd put close somewhere at 0.1 or 0.01 -- The received wisdom is one or two orders of magnitude smaller than to your desired accurary.

​​​​​​​Note that this accuracy does not having anything to do with how good your interpolation is with regards to the actual field: there's no geostatistical model or something like it involved. It's just doing interpolation with Laplace's equation. It approximately solves a system of equations to do this, and the accuracy refers to how close to exact that solution is (to for example, a direct (Gauss-Seidel) method).

**Comment by Manangka** [comment]
In GitLab by @Huite on Jun 1, 2021, 22:33

I was not able to fix it *quickly*, but I was able to fix it...

With this commit:
50c8282dd9be4f5dcca7d41ffce971390b8b03d7
