### ISSUE TITLE
imod-wq: missing packages should give clear errors

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#193]
In GitLab by @Huite on Oct 18, 2021, 13:42

```python
C:\Miniconda3\envs\main\lib\site-packages\dask\utils.py:34: RuntimeWarning: All-NaN slice encountered
  return func(*args, **kwargs)
C:\Miniconda3\envs\main\lib\site-packages\dask\core.py:121: RuntimeWarning: All-NaN slice encountered
  return func(*(_execute_task(a, cache) for a in args))
Traceback (most recent call last):
  File "src\1-prepare\clip_modeldomain.py", line 235, in <module>
    ml.write(f"data/3-input/{modelname}", result_dir="data/4-output")
  File "d:\src\imod-python\imod\wq\model.py", line 746, in write
    runfile_content = self.render(
  File "d:\src\imod-python\imod\wq\model.py", line 625, in render
    if isinstance(self[advkey], (imod.wq.AdvectionMOC, imod.wq.AdvectionHybridMOC)):
  File "C:\Miniconda3\envs\main\lib\collections\__init__.py", line 1010, in __getitem__
    raise KeyError(key)
KeyError: None
```

The error here should be:

```python
raise ValueError("Missing required package: adv")
```

Or something along those lines.

**Comment by JoerivanEngelen** [comment]
No developments are planned for the ``wq`` module.
