### ISSUE TITLE
KeyError trying to clip Seawat model object.

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#236]
In GitLab by @judeking on May 5, 2022, 16:14

Clipping a SeawatModel object gives KeyError:

```
Traceback (most recent call last):

  File "C:\Users\king_je\AppData\Local\Temp\ipykernel_21320\1208465070.py", line 2, in <cell line: 1>
    ml = ml.clip(extent, head, conc)

  File "C:\Users\king_je\AppData\Local\mambaforge\lib\site-packages\imod\wq\model.py", line 916, in clip
    ml = self.sel(**clip_slices)

  File "C:\Users\king_je\AppData\Local\mambaforge\lib\site-packages\imod\wq\model.py", line 83, in sel
    selmodel[pkgname].dataset = pkg.dataset.loc[sel_dims]

  File "C:\Users\king_je\AppData\Local\mambaforge\lib\collections\__init__.py", line 1058, in __getitem__
    raise KeyError(key)

KeyError: 'bas'
```

#%%

Example code:

```python
import imod
import xarray as xr


path_interim_lhmzz = r"p:\11203718-007-nhi-zoetzout\LHMzz_v4.1_results\LHM_as_netcdf"
path_LHM41_results = path_interim_lhmzz + r"/autonomous"

model_x = 120_000
model_y = 530_000
model_radius = 10_000


head = xr.open_zarr(path_LHM41_results + rf"/head.zarr")
conc = xr.open_zarr(path_LHM41_results + rf"/conc.zarr")


extent = (model_x - model_radius, model_x + model_radius, model_y - model_radius, model_y + model_radius)


ml = imod.wq.SeawatModel("tmp")
ml["bas"] = imod.wq.BasicFlow.from_file(
    path_interim_lhmzz  + r"/bas.nc", chunks={"layer": 1}
)



# Clip
with imod.util.ignore_warnings():
    ml = ml.clip(extent, head, conc)
```

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on May 5, 2022, 16:33

I see one dumb mistake I made here, but I don't think it will fix your issue:

https://gitlab.com/deltares/imod/imod-python/-/blob/master/imod/wq/model.py#L80

```python
if pkgname == "bas6":
```

Should be:
```python
if pkg._pkg_id == "bas6":
```

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on May 10, 2022, 10:54

After some communication with Jude, it appeared he was using the latest release, and not the development version. This one includes the fix I made. It'd be good to do a new release.

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on May 10, 2022, 12:08

FYI: I fixed my mistake in this commit https://gitlab.com/deltares/imod/imod-python/-/commit/90c8aae41326bc2f01e66235b853b1b545ab03f5
