### ISSUE TITLE
Fix failing plot_map example

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#567]
On the build server and locally the plot_map.py example is failing.

Gitlab CI output:
```
generating gallery for examples/visualize... [100%] plot_map.py
WARNING: /builds/deltares/imod/imod-python/examples/visualize/plot_map.py failed to execute correctly: Traceback (most recent call last):
  File "/builds/deltares/imod/imod-python/examples/visualize/plot_map.py", line 55, in <module>
    imod.visualize.plot_map(
  File "/builds/deltares/imod/imod-python/imod/visualize/spatial.py", line 270, in plot_map
    ctx.add_basemap(ax=ax, source=source, crs=crs, **kwargs_basemap)
  File "/opt/conda/envs/imod/lib/python3.10/site-packages/contextily/plotting.py", line 129, in add_basemap
    image, extent = bounds2img(
  File "/opt/conda/envs/imod/lib/python3.10/site-packages/contextily/tile.py", line 225, in bounds2img
    merged, extent = _merge_tiles(tiles, arrays)
  File "/opt/conda/envs/imod/lib/python3.10/site-packages/contextily/tile.py", line 628, in _merge_tiles
    img[y * h : (y + 1) * h, x * w : (x + 1) * w, :] = arr
ValueError: could not broadcast input array from shape (512,512,4) into shape (256,256,4)
Extension error (sphinx_gallery.gen_gallery):
Handler <function generate_gallery_rst at 0x7f38ecec5b40> for event 'builder-inited' threw an exception (exception: could not broadcast input array from shape (512,512,4) into shape (256,256,4))
make: *** [Makefile:20: html] Error 2
```

**Comment by Manangka** [comment]
mentioned in commit 48d049db4d547c2df73d0369e4bf6cd9effa0d7f

**Comment by Manangka** [comment]
In GitLab by @hibajamal on Oct 8, 2023, 22:06

I've been getting the same problem for the last few days, even though the same contextily code has been running absolutely fine for the past few weeks! Which map tiles have you been using?

**Comment by Manangka** [comment]
changed the incident status to **Resolved** by closing the incident
